Improve pt script to allow for single test-cases to be run.
This patch adds two changes:
Instead of defaulting to a ./Test binary (these aren't built anymore),
take the non-parameter argument as program name. If multiple are
specified, the last one will be picked - don't do that.

export TET_RESFILE as <programname>.log by default unless it's already
set in the environment.

Example use case now:
$> pt XGrabButton
will generate XGrabButton.log

Signed-off-by: Peter Hutterer <peter.hutterer@who-t.net>

diff --git a/xts5/src/bin/scripts/pt b/xts5/src/bin/scripts/pt
--- a/xts5/src/bin/scripts/pt
+++ b/xts5/src/bin/scripts/pt
@@ -19,13 +19,6 @@
 
 trap "rm -f CONFIG" 0
 
-PROG=./Test
-if [ ! -f $PROG ]; then
-	# If there isn't a ./Test then try for the space saving name.
-	THISDIR=`pwd`
-	PROG=./`basename $THISDIR`
-fi
-
 ICS=
 echo > CONFIG
 
@@ -66,9 +59,18 @@ do
 	-m)
 		PROG=./MTest
 		;;
+	*)
+		PROG=$1
+		;;
 	esac
 	shift
 done
+
+if [ ! -f "$PROG" ]; then
+	echo "Cannot find test run '$PROG'";
+	exit 1
+fi
+
 
 # config=${TET_CONFIG:-$TET_ROOT/xts5/tetexec.cfg}
 # Since :- is not universal, and I really want that functionality.
@@ -76,6 +78,11 @@ if [ x"$TET_CONFIG" = x"" ]; then
 	config=$TET_ROOT/xts5/tetexec.cfg
 else
 	config=$TET_CONFIG
+fi
+
+if [ -z "$TEST_RESFILE" ]; then
+	TET_RESFILE=$PROG.log
+	export TET_RESFILE
 fi
 
 cat $config >> CONFIG
